# Generated by Django 2.2.15 on 2020-09-06 17:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_view_courier_tab', 'Can view courier tab'), ('can_view_cashier_tab', 'Can view cashier tab'), ('can_view_operator_tab', 'Can view operator tab'), ('can_view_head_operator_tab', 'Can view head operator tab'), ('can_view_tech_stuff_tab', 'Can view tech stuff tab'), ('can_view_customer_tab', 'Can view customer tab')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Пасспортные данные'),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=255, verbose_name='Дом')),
                ('flat', models.IntegerField(blank=True, null=True, verbose_name='квартира')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('enter_key', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Enter keys')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.City')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.District')),
                ('street', models.ForeignKey(max_length=255, on_delete=django.db.models.fields.Empty, to='api.Street', verbose_name='Улица')),
            ],
        ),
    ]
