# Generated by Django 2.2.15 on 2020-09-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200906_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('type', models.CharField(choices=[('moto', 'мото'), ('car', 'авто')], max_length=50)),
                ('vin_code', models.CharField(max_length=100, unique=True)),
                ('gov_number', models.CharField(max_length=20, unique=True)),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='vehicle number')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
