# Generated by Django 2.2.15 on 2020-09-06 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Address', verbose_name='Адрес СТО')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
