# Generated by Django 2.2.15 on 2020-09-18 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200916_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', related_query_name='address', to='api.City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', related_query_name='address', to='api.District'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.fields.Empty, related_name='addresses', related_query_name='address', to='api.Street', verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='couriershift',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_shifts', related_query_name='courier_shift', to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='couriershift',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier_shifts', related_query_name='courier_shift', to='api.Vehicle', verbose_name='Транспортное средство'),
        ),
        migrations.AlterField(
            model_name='couriershiftexpenses',
            name='courier_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_shift_expenses', related_query_name='courier_shift_expenses', to='api.CourierShift', verbose_name='Смена курьера'),
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', related_query_name='district', to='api.City'),
        ),
        migrations.AlterField(
            model_name='technicalservice',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tech_services', related_query_name='tech_service', to='api.Address', verbose_name='Адрес СТО'),
        ),
        migrations.AlterField(
            model_name='vehicleservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.fields.Empty, related_name='vehicle_services', related_query_name='vehicle_service', to='api.TechnicalService'),
        ),
        migrations.AlterField(
            model_name='vehicleservice',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.fields.Empty, related_name='vehicle_service', related_query_name='vehicle_service', to='api.Vehicle'),
        ),
        migrations.CreateModel(
            name='UserFines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('amount', models.IntegerField(default=0, verbose_name='Сумма штрафа')),
                ('fines', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Fines', verbose_name='Штрафы пользователя')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': '-created_at',
                'abstract': False,
            },
        ),
    ]
