# Generated by Django 2.2.15 on 2020-10-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201001_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorshift',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='operatorshift',
            name='start_time',
        ),
    ]
