# Generated by Django 2.2.15 on 2020-10-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201004_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorshift',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец смены'),
        ),
        migrations.AddField(
            model_name='operatorshift',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало смены'),
        ),
    ]
